[project]
org-name = "wso2"
version = "0.9.18"
license = "Apache-2.0"
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/package-twitter"
keywords = ["ballerina", "Twitter", "endpoint", "connector"]
