[project]
org-name = "wso2"
version = "0.9.27"
license = "Apache-2.0"
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/module-twitter"
keywords = ["ballerina", "Twitter", "client", "connector"]
